name: wallpaper_app
description: A 4K & HD Wallpaper App
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  cached_network_image: ^3.2.3
  google_mobile_ads: ^3.3.0
  path_provider: ^2.0.17
  shared_preferences: ^2.1.1
  connectivity_plus: ^4.2.2
  flutter_wallpaper_manager: ^0.0.8
  gallery_saver: ^2.3.2
  permission_handler: ^11.1.0
  url_launcher: ^6.2.13
  hive: ^2.2.3
  hive_flutter: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
