name: wallpaper_app
description: A 4K & HD Wallpaper app with Pexels API, Ads, and Hive favorites.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking
  http: ^1.2.2
  connectivity_plus: ^6.0.3
  url_launcher: ^6.3.1

  # UI & Images
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  gallery_saver: ^2.3.2
  wallpaper_manager_flutter: ^1.0.3
  permission_handler: ^11.4.0

  # Local Storage
  shared_preferences: ^2.3.2
  hive: ^2.3.2
  hive_flutter: ^1.1.0

  # Ads
  google_mobile_ads: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.10
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
