name: wallpaper_app
description: A beautiful 4K & HD wallpaper app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  http: ^1.1.0
  google_mobile_ads: ^3.0.0
  path_provider: ^2.0.14
  shared_preferences: ^2.1.0
  connectivity_plus: ^4.1.0
  wallpaper_manager_plus: ^0.3.0
  gallery_saver: ^2.3.0
  permission_handler: ^11.3.0
  url_launcher: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
