name: wallpaper_app
description: A beautiful 4K & HD wallpaper app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  http: ^0.13.6
  google_mobile_ads: ^5.3.1
  path_provider: ^2.0.12
  shared_preferences: ^2.3.0
  connectivity_plus: ^7.0.0
  wallpaper_manager_plus: ^0.0.4
  gallery_saver: ^2.3.0
  permission_handler: ^11.3.0
  url_launcher: ^6.3.0
  hive: ^2.2.0
  hive_flutter: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
