name: wallpaper_app
description: A 4K & HD Wallpaper app with Pexels API, Ads, and Hive favorites.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking
  http: ^1.1.2
  connectivity_plus: ^4.1.1
  url_launcher: ^6.2.10

  # UI & Images
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.6.3
  gallery_saver: ^2.3.2
  wallpaper_manager_flutter: ^1.0.4
  permission_handler: ^11.4.0

  # Local Storage
  shared_preferences: ^2.1.3
  hive: ^2.3.3
  hive_flutter: ^1.1.1

  # Ads
  google_mobile_ads: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.1.0
  build_runner: ^2.4.2
  flutter_launcher_icons: ^0.11.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
