name: wallpaper_app
description: A 4K & HD wallpaper app
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cached_network_image: ^3.2.3
  google_mobile_ads: ^3.2.0
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  connectivity_plus: ^4.0.2
  wallpaper_manager_plus: ^2.0.4
  gallery_saver: ^2.3.2
  permission_handler: ^11.3.1
  url_launcher: ^6.1.12
  hive: ^2.2.3
  hive_flutter: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

# ------------------ Flutter Launcher Icons ------------------
flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
