name: wallpaper_app
description: 4K & HD Wallpapers App
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking (compatible with gallery_saver)
  http: ^0.13.6
  connectivity_plus: ^4.0.2
  url_launcher: ^6.1.12

  # UI & Image Caching
  cached_network_image: ^3.2.3

  # Ads
  google_mobile_ads: ^3.2.0

  # Storage & Local DB
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Wallpaper & Gallery
  wallpaper_manager_plus: ^2.0.1
  gallery_saver: ^2.3.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
