name: Flutter Android Build (Professional)

on:
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      # 3️⃣ Get Dependencies
      - name: Flutter pub get
        run: flutter pub get

      # 4️⃣ Ensure Android v2 embedding
      - name: Ensure Android v2 embedding
        run: flutter create . --platforms=android

      # 5️⃣ Add INTERNET permission
      - name: Add INTERNET permission
        run: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          if ! grep -q 'android.permission.INTERNET' "$MANIFEST"; then
            sed -i '/<manifest /a \ \ <uses-permission android:name="android.permission.INTERNET"/>' "$MANIFEST"
            echo "INTERNET permission added."
          else
            echo "INTERNET permission already present."
          fi

      # 6️⃣ Replace launcher icon with assets/logo.png
      - name: Replace App Icon
        run: |
          ICON_DIR="android/app/src/main/res/mipmap-*/ic_launcher.png"
          if [ -f "assets/logo.png" ]; then
            for f in $ICON_DIR; do
              cp assets/logo.png $f
            done
            echo "App icon replaced."
          else
            echo "assets/logo.png not found, skipping icon replacement."
          fi

      # 7️⃣ Flutter Clean
      - name: Flutter Clean
        run: flutter clean

      # 8️⃣ Build APK
      - name: Build APK
        run: flutter build apk --release

      # 9️⃣ Build AAB
      - name: Build AAB
        run: flutter build appbundle --release

      # 🔟 Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # 1️⃣1️⃣ Upload AAB artifact
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
