name: Flutter Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Remove Old Android Folder (if exists)
        run: |
          if [ -d "android" ]; then
            rm -rf android
            echo "🗑️ Old Android folder removed."
          fi

      - name: Create Fresh Android Folder (v2 embedding)
        run: |
          flutter create --org com.manii.wallpapper --project-name=hd_wallpaper --platforms=android .
          echo "✅ Fresh Android folder created."

      - name: Replace Flutter Default Logo
        run: |
          for dpi in xxxhdpi xxhdpi xhdpi hdpi mdpi; do
            mkdir -p android/app/src/main/res/mipmap-$dpi/
            cp assets/logo.png android/app/src/main/res/mipmap-$dpi/ic_launcher.png
          done
          echo "🎨 Launcher icon replaced with assets/logo.png"

      - name: Enable INTERNET Permission
        run: |
          manifest="android/app/src/main/AndroidManifest.xml"
          if ! grep -q "android.permission.INTERNET" "$manifest"; then
            sed -i '/<manifest /a\    <uses-permission android:name="android.permission.INTERNET" />' $manifest
            echo "🌐 INTERNET permission added."
          else
            echo "✅ INTERNET permission already present."
          fi

      # ✅ Patch gallery_saver AFTER android folder creation
      - name: Fix Gallery Saver Namespace
        run: |
          GALLERY_SAVER_PATH=$(find $HOME/.pub-cache/hosted/pub.dev -type d -name "gallery_saver-*" | head -n 1)
          if [ -n "$GALLERY_SAVER_PATH" ]; then
            echo "🧩 Patching gallery_saver at: $GALLERY_SAVER_PATH"
            if ! grep -q "namespace" "$GALLERY_SAVER_PATH/android/build.gradle"; then
              sed -i '/apply plugin: "com.android.library"/a\
              android {\n    namespace "carnegietechnologies.gallery_saver"\n}' "$GALLERY_SAVER_PATH/android/build.gradle"
              echo "✅ Namespace added successfully."
            else
              echo "✅ Namespace already exists."
            fi
          else
            echo "⚠️ gallery_saver plugin not found."
          fi

      - name: Clean Previous Builds
        run: flutter clean

      - name: Build APK
        run: flutter build apk --release --no-shrink

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build AAB
        run: flutter build appbundle --release --no-shrink

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
