name: Flutter Android Release Build (APK + AAB)

on:
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2️⃣ Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      # 3️⃣ Enable flutter analytics (optional, ignore if not wanted)
      - name: Disable Analytics (Optional)
        run: flutter config --no-analytics

      # 4️⃣ Get dependencies
      - name: Flutter Pub Get
        run: flutter pub get

      # 5️⃣ Ensure Android v2 embedding
      - name: Ensure Android v2 embedding
        run: flutter create . --platforms=android

      # 6️⃣ Add INTERNET permission if missing
      - name: Add INTERNET permission
        run: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          if ! grep -q 'android.permission.INTERNET' "$MANIFEST"; then
            sed -i '/<manifest /a \ \ <uses-permission android:name="android.permission.INTERNET"/>' "$MANIFEST"
            echo "INTERNET permission added."
          else
            echo "INTERNET permission already present."
          fi

      # 7️⃣ Replace launcher icon
      - name: Replace App Icon
        run: |
          ICON_DIR="android/app/src/main/res/mipmap-*/ic_launcher.png"
          if [ -f "assets/logo.png" ]; then
            for f in $ICON_DIR; do
              cp assets/logo.png $f
            done
            echo "App icon replaced with assets/logo.png"
          else
            echo "assets/logo.png not found, skipping icon replacement"
          fi

      # 8️⃣ Flutter clean
      - name: Flutter Clean
        run: flutter clean

      # 9️⃣ Flutter pub get (after clean)
      - name: Flutter Pub Get (post-clean)
        run: flutter pub get

      # 🔟 Build APK Release
      - name: Build APK Release
        run: |
          set -e
          echo "Building APK release..."
          flutter build apk --release --target-platform android-arm,android-arm64,android-x64
          echo "APK build completed."

      # 1️⃣1️⃣ Build AAB Release
      - name: Build AAB Release
        run: |
          set -e
          echo "Building AAB release..."
          flutter build appbundle --release
          echo "AAB build completed."

      # 1️⃣2️⃣ Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # 1️⃣3️⃣ Upload AAB artifact
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
