name: Flutter Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Remove Old Android Folder (if exists)
        run: |
          if [ -d "android" ]; then
            rm -rf android
            echo "🗑️ Old Android folder removed."
          fi

      - name: Create Fresh Android Folder (v2 embedding)
        run: |
          flutter create --org com.manii.wallpapper --project-name=hd_wallpaper --platforms=android .
          echo "✅ Fresh Android folder created."

      - name: Replace Launcher Icons
        run: |
          for dpi in mdpi hdpi xhdpi xxhdpi xxxhdpi; do
            DEST="android/app/src/main/res/mipmap-$dpi/ic_launcher.png"
            mkdir -p $(dirname $DEST)
            cp assets/logo.png $DEST
          done
          for icon_type in foreground background; do
            DEST_ADAPTIVE="android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_$icon_type.png"
            mkdir -p $(dirname $DEST_ADAPTIVE)
            cp assets/logo.png $DEST_ADAPTIVE
          done
          echo "🎨 Launcher icons replaced."

      - name: Add Required Permissions
        run: |
          manifest="android/app/src/main/AndroidManifest.xml"
          declare -a perms=("INTERNET" "WRITE_EXTERNAL_STORAGE" "READ_EXTERNAL_STORAGE" "ACCESS_NETWORK_STATE" "FOREGROUND_SERVICE")
          for p in "${perms[@]}"; do
            if ! grep -q "android.permission.$p" "$manifest"; then
              sed -i "/<manifest /a\    <uses-permission android:name=\"android.permission.$p\" />" $manifest
              echo "✅ Permission $p added."
            else
              echo "✅ Permission $p already present."
            fi
          done

      - name: Fix Gallery Saver Namespace (AGP 8+)
        run: |
          GALLERY_SAVER_PATH=$(find $HOME/.pub-cache/hosted/pub.dev -type d -name "gallery_saver-*" | head -n 1)
          if [ -d "$GALLERY_SAVER_PATH/android" ]; then
            GRADLE_FILE="$GALLERY_SAVER_PATH/android/build.gradle"
            if ! grep -q "namespace" "$GRADLE_FILE"; then
              echo '
              android {
                namespace "carnegietechnologies.gallery_saver"
              }
              ' >> "$GRADLE_FILE"
              echo "✅ Namespace added to gallery_saver"
            else
              echo "✅ Namespace already present in gallery_saver"
            fi
          else
            echo "⚠️ gallery_saver plugin not found"
          fi

      - name: Clean Previous Builds
        run: flutter clean

      - name: Build APK
        run: flutter build apk --release --no-shrink

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build AAB
        run: flutter build appbundle --release --no-shrink

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
