name: Flutter Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter (latest stable 2025)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4' # latest stable with Dart 3.3+

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Remove Old Android Folder (if exists)
        run: |
          if [ -d "android" ]; then
            rm -rf android
            echo "🧹 Old Android folder removed."
          fi

      - name: Create Fresh Android Folder (v2 embedding)
        run: |
          flutter create --androidx --project-name=wallpaper_app --org=com.manii --platforms=android .
          echo "✅ Fresh Android folder created (v2 embedding)."

      - name: Update App Name & Package
        run: |
          gradle_file="android/app/build.gradle"
          manifest="android/app/src/main/AndroidManifest.xml"
          app_name="4K & HD Wallpaper"

          # Update package name in build.gradle
          sed -i 's/applicationId "com.example.wallpaper_app"/applicationId "com.manii.wallpapper"/' $gradle_file

          # Update app name in strings.xml
          sed -i 's/flutter_application_name/'"$app_name"'/' android/app/src/main/res/values/strings.xml

          echo "✅ Package name & app name updated."

      - name: Replace Flutter Default Logo
        run: |
          for dpi in xxxhdpi xxhdpi xhdpi hdpi mdpi; do
            mkdir -p android/app/src/main/res/mipmap-$dpi/
            cp assets/logo.png android/app/src/main/res/mipmap-$dpi/ic_launcher.png
          done
          echo "🎨 Launcher icon replaced with assets/logo.png"

      - name: Enable INTERNET Permission
        run: |
          manifest="android/app/src/main/AndroidManifest.xml"
          if ! grep -q "android.permission.INTERNET" "$manifest"; then
            sed -i '/<manifest /a\    <uses-permission android:name="android.permission.INTERNET" />' $manifest
            echo "🌐 INTERNET permission added."
          else
            echo "🌐 INTERNET permission already present."
          fi

      - name: Clean Project
        run: flutter clean

      - name: Build APK
        run: flutter build apk --release --no-shrink

      - name: Build AAB
        run: flutter build appbundle --release --no-shrink

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
