name: Flutter Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Remove Old Android Folder (if exists)
        run: |
          if [ -d "android" ]; then
            rm -rf android
            echo "Old Android folder removed."
          fi

      - name: Create Android Folder (v2 embedding)
        run: |
          flutter create --org com.manii.wallpapper --project-name=hd_wallpaper --platforms=android .
          echo "Fresh Android folder created with v2 embedding."

      - name: Replace Flutter Default Logo
        run: |
          for dpi in xxxhdpi xxhdpi xhdpi hdpi mdpi; do
            mkdir -p android/app/src/main/res/mipmap-$dpi/
            cp assets/logo.png android/app/src/main/res/mipmap-$dpi/ic_launcher.png
          done
          echo "Launcher icon replaced with assets/logo.png"

      - name: Enable INTERNET Permission
        run: |
          manifest="android/app/src/main/AndroidManifest.xml"
          if ! grep -q "android.permission.INTERNET" "$manifest"; then
            sed -i '/<manifest /a\    <uses-permission android:name="android.permission.INTERNET" />' $manifest
            echo "INTERNET permission added."
          else
            echo "INTERNET permission already present."
          fi

      - name: Clean Previous Builds
        run: flutter clean

      - name: Build APK
        run: flutter build apk --release --no-shrink

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build AAB
        run: flutter build appbundle --release --no-shrink

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
